@startuml Slack_slash_command
box docker #LightBlue
participant "streaming-server"
participant "image-storage"
participant slack
end box

participant Slack
participant Client

Client -> Slack : Slash command
Slack -> slack : POST

slack --> Slack : Response
Slack --> Client : 転送

slack -> "image-storage": 画像変換要求
"image-storage" --> slack: 画像IDをResponse
slack ->Slack: 投稿
Slack --> slack: OK

"image-storage" -> "streaming-server": ストリーミング受信要求
"streaming-server" --> "image-storage": Response
"image-storage" -> "image-storage": 写真保存

== 表示タイミング ==

Client -> Slack: 表示要求
Slack --> Client: Response

== 画像表示タイミング ==
Client -> slack: GET
slack -> "image-storage": 画像要求
"image-storage" -> "image-storage": 画像取得
"image-storage" --> slack: Response
slack --> Client: Response
@enduml
