@startuml Slack_button
box docker #LightBlue
participant "streaming-server"
participant slack
end box

participant Slack
participant Client

Client -> Slack: Buttonを押す
Slack -> slack: POST

slack --> Slack : Response
Slack --> Client : 転送

slack -> Slack: 削除
Slack --> slack: OK
@enduml
