@startuml Startup
box docker #LightBlue
participant media
participant "streaming-server"
participant streamer
participant tunnel
end box

loop
	streamer -> "streaming-server": ストリーミング配信
end

loop
	media -> "streaming-server" : ストリーミング受信要求
	"streaming-server" --> media : Respose
	media -> media : ファイル生成
end

tunnel -> ngrok : 設定
ngrok --> tunnel : OK

tunnel -> AWS : 設定
AWS --> tunnel : OK
@enduml
