@startuml WEB

box docker #LightBlue
database redis
participant hls
participant "image-storage"
participant web
end box

participant Slack
participant Client

Client -> web : GET

alt 認証情報が古い
	web -> redis: token取得
	note right: Clientで保存されていたキーを利用

	redis --> web: Response
	web -> Slack: 権限確認

	Slack --> web: Response
end

alt 画像
	web -> "image-storage": 動画, 写真の取得
	"image-storage" -> "image-storage": 取得
	"image-storage" --> web: Response
else 動画
	web -> hls: 動画の取得
	hls -> hls: 取得
	hls --> web: Response
end


web --> Client : Response
@enduml
