@startuml WEB

box docker #LightBlue
database redis
participant media
participant web
end box

participant Slack
participant Client

Client -> web : GET

alt 認証情報が古い
	web -> redis: token取得
	note right: Clientで保存されていたキーを利用

	redis --> web: Response
	web -> Slack: 権限確認

	Slack --> web: Response
end

web -> media: 動画, 写真の取得
media -> media: 取得
media --> web: Response

web --> Client : Response
@enduml
