@startuml WEB_login
box docker #LightBlue
database redis
participant web
end box

participant Slack
participant Client

Client -> web : GET

web --> Client : Redirect
note right: Slackで認証するためリダイレクト

Client -> Slack : GET
Slack --> Client: Redirect
note right
	WEB Server 宛に一時token
	をリダイレクト
end note

Client -> web : GET
web -> Slack : access token要求
Slack --> web : Response

web -> redis: access token保存

web --> Client: Response
note right
	redisに保存したtokenに対応する
	keyを暗号化して保存
end note
@enduml
